/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimuladoRouteImport } from './routes/simulado'
import { Route as IndexRouteImport } from './routes/index'

const SimuladoRoute = SimuladoRouteImport.update({
  id: '/simulado',
  path: '/simulado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simulado': typeof SimuladoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simulado': typeof SimuladoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/simulado': typeof SimuladoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simulado'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simulado'
  id: '__root__' | '/' | '/simulado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimuladoRoute: typeof SimuladoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulado': {
      id: '/simulado'
      path: '/simulado'
      fullPath: '/simulado'
      preLoaderRoute: typeof SimuladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimuladoRoute: SimuladoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
